services:
  # Frontend Static Site
  - type: static
    name: sri-senthoor-granites-frontend
    buildCommand: npm --prefix frontend run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: sri-senthoor-granites-backend
    runtime: node
    buildCommand: npm --prefix backend run build
    startCommand: npm --prefix backend run start
    envVars:
      - key: NODE_ENV
        value: production

