export const COMPANY_INFO = {
  name: 'Sri Senthoor Granites',
  tagline: 'Crafting Architectural Timelessness',
  slogan: 'Your choice is our priority',
  founder: 'Arshath',
  established: 2023,
  phones: ['+91 674227978', '+91 7200629846'],
  rawPhones: ['674227978', '7200629846'],
  email: 'contact@srisenthoorgranites.com',
  address: {
    doorNo: 'No.261/1B2',
    area: 'Ariyamangalam',
    landmark: 'Palpannai, Thanjavur Bypass',
    city: 'Trichy',
    pincode: '620010',
    full: 'No.261/1B2, Ariyamangalam, Palpannai, Thanjavur Bypass, Trichy – 620010',
    mapUrl: 'https://maps.google.com/?q=No.261/1B2,+Ariyamangalam,+Palpannai,+Thanjavur+Bypass,+Trichy+620010',
  },
  workingHours: 'Mon - Sat: 9:00 AM - 8:30 PM | Sun: 10:00 AM - 5:00 PM',
};

export const PRODUCT_CATEGORIES = [
  {
    id: 'granites',
    title: 'Granites',
    subtitle: 'Premium Quarry Slabs & Custom Cuts',
    description: 'High-density natural granite slabs selected for superior durability, vein elegance, and high-gloss polish for luxury countertops, flooring, and exterior facades.',
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    features: ['Heat & Scratch Resistant', 'Zero Water Absorption', 'Custom Edge Profiles', 'Polished & Flamed Finishes'],
    specs: { thickness: '18mm - 30mm', origin: 'Direct Quarry Select', finish: 'High Gloss / Leather / Satin' },
  },
  {
    id: 'vitrified-tiles',
    title: 'Vitrified Tiles',
    subtitle: 'Ultra-Large Format Architectural Porcelain',
    description: 'Precision-engineered vitrified tiles offering seamless marble patterns, stain resistance, and high foot-traffic endurance for contemporary interior spaces.',
    icon: 'Grid',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    features: ['Stain & Chemical Resistant', 'Seamless Rectified Edges', 'High Breaking Strength', 'Silk & Matte Surfaces'],
    specs: { sizes: '1200x2400mm, 800x1600mm', waterAbsorption: '<0.05%', finish: 'Full Body Vitrified' },
  },
  {
    id: 'kadappa',
    title: 'Kadappa',
    subtitle: 'Traditional Natural Black Stone Elegance',
    description: 'Authentic Cuddapah black limestone offering slip-resistant matte textures, ideal for serene courtyard flooring, steps, wall cladding, and heritage spaces.',
    icon: 'Square',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    features: ['Natural Non-Slip Texture', 'Thermal Insulation', 'Authentic Deep Black Tone', 'All-Weather Resilience'],
    specs: { thickness: '20mm - 40mm', style: 'Rough Machine Cut / Calibration', use: 'Indoor & Outdoor' },
  },
  {
    id: 'sanitary-wares',
    title: 'Sanitary Wares',
    subtitle: 'Designer Ceramic Basins & Water Closets',
    description: 'Ultra-hygienic glazed ceramic basins, wall-hung toilets, and freestanding bath sculptures engineered with antibacterial glazes and whisper-quiet flush technology.',
    icon: 'Bath',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    features: ['Nano-Glaze Antibacterial Surface', 'Water-Saving Dual Flush', 'Soft-Close Mechanism', 'Contemporary Ergonomics'],
    specs: { material: 'Vitreous China Ceramic', warranty: '10-Year Surface Guarantee', certification: 'ISO Premium' },
  },
  {
    id: 'bath-fittings',
    title: 'Bath Fittings',
    subtitle: 'Precision Brass Faucets & Hydrotherapies',
    description: 'Luxury thermostatic brassware, waterfall showerheads, and PVD gold & matte black faucets crafted for opulent bathroom suites.',
    icon: 'Droplets',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80',
    features: ['PVD Anti-Tarnish Coating', 'Ceramic Disc Cartridges', 'Aerated Soft Stream', 'Precision Temperature Control'],
    specs: { material: 'Solid Lead-Free Brass', finishes: 'Rose Gold, Matte Black, Brushed Platinum', pressure: 'High Flow' },
  },
];

export const GALLERY_ITEMS = [
  {
    id: 'g1',
    category: 'granites',
    title: 'Black Galaxy Granite Island',
    subtitle: 'Trichy Villa Countertop Installation',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    aspect: 'tall',
  },
  {
    id: 'g2',
    category: 'vitrified-tiles',
    title: 'Calacatta Onyx Vitrified Suite',
    subtitle: 'Modern Living Floor Hall',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    aspect: 'wide',
  },
  {
    id: 'g3',
    category: 'bath-fittings',
    title: 'Brushed Gold Cascade System',
    subtitle: 'Penthouse Bath Suite',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1000&q=80',
    aspect: 'tall',
  },
  {
    id: 'g4',
    category: 'kadappa',
    title: 'Heritage Kadappa Courtyard Step',
    subtitle: 'Architectural Stone Deck',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80',
    aspect: 'square',
  },
  {
    id: 'g5',
    category: 'sanitary-wares',
    title: 'Freestanding Stone Ceramic Basin',
    subtitle: 'Custom Master Bathroom',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
    aspect: 'tall',
  },
  {
    id: 'g6',
    category: 'granites',
    title: 'Kashmir White Granite Facade',
    subtitle: 'Exterior Exterior Cladding',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80',
    aspect: 'wide',
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'R. Kanthasamy',
    role: 'Principal Architect, DesignStudio Trichy',
    content: 'Sri Senthoor Granites supplied mirror-polished black granite slabs for our luxury estate project. Founder Arshath’s commitment to quality stone selection and precision slab calibration is unmatched in Tamil Nadu.',
    rating: 5,
    project: 'Private Estate, Thanjavur',
  },
  {
    id: 't2',
    name: 'Dr. Meena Swaminathan',
    role: 'Homeowner',
    content: 'We sourced all our living room vitrified tiles and luxury rose gold bath fittings from Sri Senthoor Granites. Their slogan "Your choice is our priority" truly reflects in how patiently they customized our slab orders!',
    rating: 5,
    project: 'Luxury Bungalow, Trichy',
  },
  {
    id: 't3',
    name: 'S. Vikram Development',
    role: 'Commercial Contractor',
    content: 'Finding authentic high-grade Kadappa stone and heavy-duty vitrified slabs in large quantities on schedule used to be a hassle. Sri Senthoor Granites delivered flawless batches right to our bypass site.',
    rating: 5,
    project: 'Commercial Complex, Palpannai',
  },
];

export const COMPANY_STATS = [
  { label: 'Slab Varieties Available', value: '150+', suffix: 'Types' },
  { label: 'Architectural Projects Completed', value: '850+', suffix: 'Homes' },
  { label: 'Square Feet Crafted', value: '2M+', suffix: 'sq.ft' },
  { label: 'Client Satisfaction Rating', value: '99.8%', suffix: 'Happy' },
];
