import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';

dotenv.config();

export const connectDB = async (): Promise<void> => {
  try {
    const connStr = process.env.MONGODB_URI || 'mongodb://localhost:27017/sri_senthoor_granites';
    console.log(`[DB] Attempting connection to MongoDB...`);
    
    await mongoose.connect(connStr, {
      serverSelectionTimeoutMS: 3000,
    });

    console.log(`[DB] MongoDB Connected Successfully: ${mongoose.connection.host}`);
    await seedInitialData();
  } catch (error: any) {
    console.warn(`[DB Warning] Could not connect to local MongoDB daemon: ${error.message}`);
    console.warn(`[DB Warning] App will operate with simulated database fallback so APIs and Dashboard function seamlessly.`);
  }
};

async function seedInitialData() {
  try {
    const { User } = await import('../models/User');
    const { Category } = await import('../models/Category');
    const { Product } = await import('../models/Product');

    // 1. Seed Users for ALL Roles (Super Admin, Admin, Staff)
    const sampleUsers = [
      {
        name: 'Arshath (Founder)',
        email: 'admin@srisenthoorgranites.com',
        role: 'super_admin',
        permissions: [
          'users:manage',
          'products:manage',
          'products:price_update',
          'categories:manage',
          'gallery:manage',
          'testimonials:manage',
          'inquiries:manage',
          'settings:manage',
          'audit:read',
        ],
        phone: '+91 98765 43210',
        designation: 'Founder & Managing Director',
        bio: 'Founder and managing director overseeing Sri Senthoor Granites quarry operations, marble import, and showroom architecture.',
        isActive: true,
      },
      {
        name: 'Showroom Admin',
        email: 'showroom@srisenthoorgranites.com',
        role: 'admin',
        permissions: [
          'products:manage',
          'products:price_update',
          'categories:manage',
          'gallery:manage',
          'testimonials:manage',
          'inquiries:manage',
          'audit:read',
        ],
        phone: '+91 98765 11223',
        designation: 'Showroom Operations Lead',
        bio: 'Oversees inventory, granite pricing displays, and customer quotation workflow.',
        isActive: true,
      },
      {
        name: 'Karthik Raja',
        email: 'karthik@srisenthoorgranites.com',
        role: 'staff',
        permissions: ['inquiries:manage', 'products:read'],
        phone: '+91 98765 99887',
        designation: 'Senior Sales Representative',
        bio: 'Handles phone inquiries, direct showroom walk-in consultations, and estimate follow-ups.',
        isActive: true,
      },
      {
        name: 'Priya Sundaram',
        email: 'priya@srisenthoorgranites.com',
        role: 'staff',
        permissions: ['products:read', 'gallery:manage'],
        phone: '+91 98765 44332',
        designation: 'Architectural Design Advisor',
        bio: 'Specializes in CAD elevation layouts, kitchen countertop matching, and custom Cuddapah stone detailing.',
        isActive: true,
      },
    ];

    const defaultPassHash = await bcrypt.hash('Admin@123456', 10);
    const staffPassHash = await bcrypt.hash('Staff@123456', 10);

    for (const u of sampleUsers) {
      const passHash = u.role === 'staff' ? staffPassHash : defaultPassHash;
      await User.findOneAndUpdate(
        { email: u.email.toLowerCase() },
        { ...u, passwordHash: passHash },
        { upsert: true, new: true }
      );
    }
    console.log(`[DB Seed] Users for all roles (Super Admin, Admin, Staff) seeded into MongoDB.`);

    // 2. Seed Categories with Banner Images
    const sampleCategories = [
      {
        id: 'granites',
        title: 'Granites',
        subtitle: 'Premium Quarry Slabs & Custom Cuts',
        description: 'High-density natural granite slabs selected for superior durability, vein elegance, and high-gloss polish.',
        icon: 'Layers',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 'vitrified-tiles',
        title: 'Vitrified Tiles',
        subtitle: 'Ultra-Large Format Architectural Porcelain',
        description: 'Precision-engineered vitrified tiles offering seamless marble patterns and stain resistance.',
        icon: 'Grid',
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 'kadappa',
        title: 'Kadappa',
        subtitle: 'Traditional Natural Black Stone Elegance',
        description: 'Authentic Cuddapah black limestone offering slip-resistant matte textures.',
        icon: 'Square',
        image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 'sanitary-wares',
        title: 'Sanitary Wares',
        subtitle: 'Designer Ceramic Basins & Water Closets',
        description: 'Ultra-hygienic glazed ceramic basins and wall-hung toilets engineered with antibacterial glazes.',
        icon: 'Bath',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        displayOrder: 4,
        isActive: true,
      },
      {
        id: 'bath-fittings',
        title: 'Bath Fittings',
        subtitle: 'Precision Brass Faucets & Hydrotherapies',
        description: 'Luxury thermostatic brassware, waterfall showerheads, and PVD gold & matte black faucets.',
        icon: 'Droplets',
        image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80',
        displayOrder: 5,
        isActive: true,
      },
    ];

    for (const cat of sampleCategories) {
      await Category.findOneAndUpdate({ id: cat.id }, cat, { upsert: true, new: true });
    }
    console.log(`[DB Seed] Product categories synced.`);

    // 3. Seed & Sync Initial Products with Sub-Categories into MongoDB
    const sampleProducts = [
      // VITRIFIED TILES
      {
        id: 'p-floor-statuario',
        slug: 'statuario-imperial-floor-tile',
        title: 'Statuario Imperial Floor Tile',
        subtitle: '800x1600mm Full-Body Glazed Tile',
        category: 'vitrified-tiles',
        subCategory: 'Floor Tiles',
        description: 'Classic Statuario Italian marble veining on ultra-dense glazed porcelain for high-traffic living rooms.',
        price: 180,
        offerPrice: 160,
        unit: 'sq.ft',
        finish: 'High Gloss Glazed',
        thickness: '9mm',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        features: ['High Gloss Mirror Shine', 'Stain & Abrasion Resistant'],
        specs: { sizes: '800x1600mm', waterAbsorption: '<0.05%', finish: 'High Gloss' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 1,
        status: 'active',
      },
      {
        id: 'p-bathroom-anti-skid',
        slug: 'anti-skid-bathroom-matte-tile',
        title: 'Royal Slate Anti-Skid Toilet & Bathroom Tile',
        subtitle: '300x600mm Slip Resistant Matte Finish',
        category: 'vitrified-tiles',
        subCategory: 'Bathroom Tiles',
        description: 'Anti-slip textured matte ceramic tile designed for wet bathroom floors and shower enclosures.',
        price: 95,
        offerPrice: 85,
        unit: 'sq.ft',
        finish: 'R11 Anti-Skid Matte',
        thickness: '8mm',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        features: ['R11 Anti-Slip Rating', 'Soap & Acid Resistant'],
        specs: { sizes: '300x600mm', use: 'Bathroom Floor & Wall', finish: 'Matte Anti-Skid' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 2,
        status: 'active',
      },
      {
        id: 'p-wall-spanish-metro',
        slug: 'spanish-marquina-wall-cladding-tile',
        title: 'Spanish Marquina Wall Cladding Tile',
        subtitle: '400x800mm High Gloss Wall Tile',
        category: 'vitrified-tiles',
        subCategory: 'Wall Tiles',
        description: 'Deep black marble design with intense white lightning veins for bathroom and kitchen feature walls.',
        price: 110,
        offerPrice: 98,
        unit: 'sq.ft',
        finish: 'High Gloss Polish',
        thickness: '8.5mm',
        image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        features: ['Stain Repellent Glaze', 'Vibrant Contrast Veining'],
        specs: { sizes: '400x800mm', use: 'Interior Wall Cladding', finish: 'Gloss' },
        stockStatus: 'in_stock',
        isFeatured: false,
        isPopular: true,
        displayOrder: 3,
        status: 'active',
      },
      {
        id: 'p-kitchen-tile-marmi',
        slug: 'carrara-kitchen-backsplash-tile',
        title: 'Carrara Statuario Kitchen Backsplash Tile',
        subtitle: '300x900mm Stain-Proof Kitchen Tile',
        category: 'vitrified-tiles',
        subCategory: 'Kitchen Tiles',
        description: 'Ultra-smooth glazed ceramic kitchen backsplash tile designed for heat and oil-splatter resistance.',
        price: 105,
        offerPrice: 92,
        unit: 'sq.ft',
        finish: 'Smooth Satin Glaze',
        thickness: '8mm',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        features: ['Oil & Heat Repellent', 'High Gloss Polish'],
        specs: { sizes: '300x900mm', use: 'Kitchen Backsplash', finish: 'Satin Glaze' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 4,
        status: 'active',
      },
      {
        id: 'p-calacatta-porcelain',
        slug: 'calacatta-onyx-vitrified-slab',
        title: 'Calacatta Onyx Vitrified Slab',
        subtitle: '1200x2400mm Architectural Porcelain',
        category: 'vitrified-tiles',
        subCategory: 'Large Slabs',
        description: 'Italian Statuario veining engineered into full-body vitrified porcelain slabs.',
        price: 240,
        offerPrice: 215,
        unit: 'sq.ft',
        finish: 'Silk Satin Finish',
        thickness: '12mm',
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        features: ['Stain & Chemical Resistant', 'Seamless Rectified Edges'],
        specs: { sizes: '1200x2400mm', waterAbsorption: '<0.05%', finish: 'Silk Satin' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 5,
        status: 'active',
      },
      {
        id: 'p-outdoor-paver',
        slug: 'heavy-duty-outdoor-parking-tile',
        title: 'Heavy Duty Textured Outdoor Parking Tile',
        subtitle: '400x400mm 16mm Heavy Vehicle Paver',
        category: 'vitrified-tiles',
        subCategory: 'Outdoor Tiles',
        description: 'High breaking strength vitrified paver tiles designed for driveways and open courtyard terraces.',
        price: 75,
        offerPrice: 65,
        unit: 'sq.ft',
        finish: 'Punch Textured Anti-Slip',
        thickness: '16mm',
        image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        features: ['High Breaking Load', 'Weather & Frost Proof'],
        specs: { sizes: '400x400mm', thickness: '16mm', finish: 'Textured Matte' },
        stockStatus: 'in_stock',
        isFeatured: false,
        isPopular: false,
        displayOrder: 6,
        status: 'active',
      },

      // GRANITES
      {
        id: 'p-black-galaxy',
        slug: 'black-galaxy-granite',
        title: 'Black Galaxy Granite',
        subtitle: 'Quarry Grade Mirror Polish',
        category: 'granites',
        subCategory: 'Black Granites',
        description: 'High-density natural black granite with golden copper specks. Zero water absorption, heat & scratch resistant.',
        price: 185,
        offerPrice: 165,
        unit: 'sq.ft',
        finish: 'High Gloss Polish',
        thickness: '18mm',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        features: ['Heat & Scratch Resistant', 'Zero Water Absorption'],
        specs: { thickness: '18mm', origin: 'Direct Quarry Select', finish: 'High Gloss Polish' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 7,
        status: 'active',
      },
      {
        id: 'p-tan-brown',
        slug: 'tan-brown-granite',
        title: 'Tan Brown Granite Slabs',
        subtitle: 'Deep Chocolate & Tan Mineral Grains',
        category: 'granites',
        subCategory: 'Countertop Slabs',
        description: 'Rich dark brown granite with black and reddish mineral crystals, ideal for kitchen countertops.',
        price: 140,
        offerPrice: 125,
        unit: 'sq.ft',
        finish: 'Mirror Polish',
        thickness: '18mm',
        image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        features: ['High Density Quartz Base', 'Stain Resistant'],
        specs: { thickness: '18mm', origin: 'Telangana Quarry', finish: 'Mirror Polish' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 8,
        status: 'active',
      },
      {
        id: 'p-kashmir-white',
        slug: 'kashmir-white-granite',
        title: 'Kashmir White Granite',
        subtitle: 'Exotic White Granite with Garnet Dots',
        category: 'granites',
        subCategory: 'Exotic Granites',
        description: 'Luminous light gray and white granite studded with rich burgundy garnet crystals.',
        price: 195,
        offerPrice: 175,
        unit: 'sq.ft',
        finish: 'High Gloss Polish',
        thickness: '20mm',
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        features: ['Low Porosity', 'Exotic Garnet Veining'],
        specs: { thickness: '20mm', origin: 'South India Quarry', finish: 'High Gloss' },
        stockStatus: 'in_stock',
        isFeatured: false,
        isPopular: true,
        displayOrder: 9,
        status: 'active',
      },

      // KADAPPA
      {
        id: 'p-kadappa-black',
        slug: 'authentic-kadappa-natural-stone',
        title: 'Authentic Cuddapah Kadappa Stone',
        subtitle: 'Traditional Natural Black Limestone',
        category: 'kadappa',
        subCategory: 'Black Kadappa',
        description: 'Non-slip natural matte black limestone ideal for outdoor steps, courtyards, and wall cladding.',
        price: 65,
        offerPrice: 55,
        unit: 'sq.ft',
        finish: 'Machine Cut Matte',
        thickness: '25mm',
        image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        features: ['Natural Non-Slip Texture', 'All-Weather Resilience'],
        specs: { thickness: '25mm - 30mm', finish: 'Machine Cut Matte', use: 'Indoor & Outdoor' },
        stockStatus: 'in_stock',
        isFeatured: false,
        isPopular: true,
        displayOrder: 10,
        status: 'active',
      },
      {
        id: 'p-kadappa-steps',
        slug: 'kadappa-machine-cut-steps',
        title: 'Kadappa Machine-Cut Stair Treads & Steps',
        subtitle: 'Calibrated Chamfered Edge Black Stone',
        category: 'kadappa',
        subCategory: 'Machine Cut Steps',
        description: 'Precision machine cut Cuddapah stone with bullnosed front edge, prepared for staircase steps.',
        price: 90,
        offerPrice: 80,
        unit: 'sq.ft',
        finish: 'Smooth Machine Cut',
        thickness: '30mm',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        features: ['Pre-Formed Bullnose Edge', 'High Impact Strength'],
        specs: { thickness: '30mm', finish: 'Calibrated Cut', origin: 'Cuddapah AP' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 11,
        status: 'active',
      },

      // SANITARY WARES
      {
        id: 'p-sanitary-basin',
        slug: 'freestanding-stone-ceramic-basin',
        title: 'Freestanding Stone Ceramic Basin',
        subtitle: 'Nano-Glaze Ceramic Suite',
        category: 'sanitary-wares',
        subCategory: 'Wash Basins',
        description: 'Ultra-hygienic glazed ceramic basin engineered with antibacterial coating.',
        price: 14500,
        offerPrice: 12800,
        unit: 'piece',
        finish: 'Glazed Ceramic',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        features: ['Nano-Glaze Surface', 'Soft-Close Ergonomics'],
        specs: { material: 'Vitreous China', warranty: '10-Year Guarantee', finish: 'Glazed Ceramic' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: false,
        displayOrder: 12,
        status: 'active',
      },
      {
        id: 'p-sanitary-toilet',
        slug: 'wall-hung-rimless-toilet-suite',
        title: 'Wall-Hung Rimless Toilet Suite',
        subtitle: 'Tornado Flush Hygienic Water Closet',
        category: 'sanitary-wares',
        subCategory: 'Water Closets',
        description: 'Space-saving wall-hung toilet with rimless 360-degree tornado flushing system.',
        price: 18900,
        offerPrice: 16500,
        unit: 'piece',
        finish: 'Antibacterial Ceramic',
        image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80',
        features: ['Rimless Hygiene Design', 'Dual Flush Water Saver'],
        specs: { material: 'Vitreous Ceramic', warranty: '10-Year Guarantee', finish: 'Antibacterial Glaze' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 13,
        status: 'active',
      },

      // BATH FITTINGS
      {
        id: 'p-bath-gold-faucet',
        slug: 'pvd-gold-thermostatic-cascade-shower',
        title: 'PVD Gold Thermostatic Shower System',
        subtitle: 'Solid Lead-Free Brass Hydrotherapy',
        category: 'bath-fittings',
        subCategory: 'Thermostatic Showers',
        description: 'Luxury thermostatic brassware waterfall showerhead in anti-tarnish PVD gold.',
        price: 28500,
        offerPrice: 24900,
        unit: 'set',
        finish: 'PVD Brushed Gold',
        image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80',
        features: ['PVD Anti-Tarnish Coating', 'Precision Temperature Control'],
        specs: { material: 'Solid Brass', finish: 'PVD Rose Gold', warranty: '12-Year Warranty' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: true,
        displayOrder: 14,
        status: 'active',
      },
      {
        id: 'p-bath-black-mixer',
        slug: 'matte-black-waterfall-basin-mixer',
        title: 'Matte Black Waterfall Basin Mixer',
        subtitle: 'Single Lever Solid Brass Tapware',
        category: 'bath-fittings',
        subCategory: 'Faucets',
        description: 'Modern tall waterfall tapware with ceramic disc cartridge and electroplated matte black finish.',
        price: 7800,
        offerPrice: 6500,
        unit: 'piece',
        finish: 'Matte Black PVD',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        features: ['Water-Saving Aerator', 'Solid Brass Body'],
        specs: { material: 'Lead-Free Brass', finish: 'Matte Black', warranty: '10-Year Warranty' },
        stockStatus: 'in_stock',
        isFeatured: true,
        isPopular: false,
        displayOrder: 15,
        status: 'active',
      },
    ];

    for (const p of sampleProducts) {
      await Product.findOneAndUpdate({ id: p.id }, p, { upsert: true, new: true });
    }
    console.log(`[DB Seed] Product catalog seeded and updated in MongoDB with subCategory fields.`);
  } catch (err: any) {
    console.error(`[DB Seed Error] ${err.message}`);
  }
}
